name: Docs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y doxygen graphviz clang
      - name: Build docs
        run: |
          RESOURCE_DIR=$(clang -print-resource-dir)
          # replace with installed location
          sed -i "s|-resource-dir=[^ ]*|-resource-dir=${RESOURCE_DIR}|" Doxyfile
          doxygen Doxyfile
      - name: Domain
        run: echo "imr.yourdomain.com" > docs/html/CNAME
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
